# (C) copyright 2019 SuperDARN Canada, University of Saskatchewan
# author: Marina Schmidt, SuperDARN Canada
site_name: RST Documentation
repo_url: https://github.com/superdarn/rst
theme: readthedocs
markdown_extensions:
    - extra
    - admonition
    - toc

pages:
- Home: index.md
- About: about.md
- Installation:
        - Linux: user_guide/linux_install.md
        - MacOSX: user_guide/mac_install.md
- RST Tutorials: 
    - Data Processing: 
            - RAWACF to FITACF: user_guide/make_fit.md
            - FITACF to GRID: user_guide/make_grid.md
            - GRID to MAP: user_guide/map_grid.md
    - Plotting Data: 
            - Range-time Plots: user_guide/time_plot.md
            - Field of View Plots: user_guide/fov_plot.md
            - Field Plots: user_guide/field_plot.md
            - Grid Plots: user_guide/grid_plot.md
            - Convection Plots: user_guide/map_plot.md
            - Customized Colors: user_guide/colors.md
- RST Developers Guide:
    - Copyrights and Licensing: developers_guide/copyright_license.md 
- SuperDARN Data Formats:
     - Dmap Data: references/general/dmap_data.md
     - IQDAT Format: references/general/iqdat.md
     - RAWACF Format: references/general/rawacf.md
     - FITACF Format: references/general/fitacf.md
     - GRID Format: references/general/grid.md
